### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by Shinena1998** [orca-zhang/ecache#7]
测试代码：
```
var c = ecache.NewLRUCache(16, 65535, 100*time.Millisecond)
func BenchmarkName(b *testing.B) {
	for i := 0; i < b.N; i++ {
		c.Put("key", "value")
	}
}
```

报错如下
```
goos: darwin
goarch: amd64
pkg: mongoTest
cpu: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
BenchmarkName
panic: runtime error: index out of range [0] with length 0

goroutine 24 [running]:
github.com/orca-zhang/ecache.(*cache).put(0xc000090300, {0x1460fa8, 0x191c108}, 0xc0000a0230, {0x0, 0x0, 0x0}, 0x16ce5d9127de9770, 0x1481be8)
	/Users/zhangbing/qiniuCloud/pkg/mod/github.com/orca-zhang/ecache@v1.1.0/ecache.go:84 +0x6b6
github.com/orca-zhang/ecache.(*Cache).put(0xc000180050, {0x1460fa8, 0x1}, 0x392c0068000c1ee8, {0x0, 0x0, 0x0})
	/Users/zhangbing/qiniuCloud/pkg/mod/github.com/orca-zhang/ecache@v1.1.0/ecache.go:165 +0x129
github.com/orca-zhang/ecache.(*Cache).Put(...)
	/Users/zhangbing/qiniuCloud/pkg/mod/github.com/orca-zhang/ecache@v1.1.0/ecache.go:179
mongoTest.BenchmarkName(0xc000168000)
	/Users/zhangbing/qiniuCloud/mongoTest/lrucache_test.go:12 +0x9b
```

看样子只要容量设置为65535，就会触发越界panic

**Comment by orca-zhang** [comment]
感谢反馈，看上去是https://github.com/orca-zhang/ecache/blob/0b78577ccbb8a70cffc80fa9f5fb8a9e69ff101f/ecache.go#L60
make里传的cap+1有溢出回转，需要向上转一个精度(比如`uint32`后+1)，我补充测试用例修复一下

**Comment by orca-zhang** [comment]
4dddf1a3fc350a11e55efbd1ce323d009099f52c 添加用例复现
8c2585121542dd674f7ec777457f62e3309e6a76 已修复
